package com.example.demo.mapper.test1;

import com.example.demo.bean.Classes;

import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ClassesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Tue Nov 12 14:43:29 CST 2024
     */
    long countByExample(ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Tue Nov 12 14:43:29 CST 2024
     */
    int deleteByExample(ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Tue Nov 12 14:43:29 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Tue Nov 12 14:43:29 CST 2024
     */
    int insert(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Tue Nov 12 14:43:29 CST 2024
     */
    int insertSelective(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Tue Nov 12 14:43:29 CST 2024
     */
    List<Classes> selectByExample(ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Tue Nov 12 14:43:29 CST 2024
     */
    Classes selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Tue Nov 12 14:43:29 CST 2024
     */
    int updateByExampleSelective(@Param("record") Classes record, @Param("example") ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Tue Nov 12 14:43:29 CST 2024
     */
    int updateByExample(@Param("record") Classes record, @Param("example") ClassesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Tue Nov 12 14:43:29 CST 2024
     */
    int updateByPrimaryKeySelective(Classes record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table classes
     *
     * @mbg.generated Tue Nov 12 14:43:29 CST 2024
     */
    int updateByPrimaryKey(Classes record);
}